### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by rwarbelow** [leiyak/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
> I'm assuming time was running short to break down the later steps into sub-steps :) However, it looks like you have a strong grasp toward the top of your file on how to break pieces down. Nice work. 
- [x] I added and committed my changes with a properly formatted commit message starting with a verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The three attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [x] The three methods I chose for **Class #1** represent behaviors or actions.
- [x] I described what the methods do in **Class 1**.
- [x] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
> This made me laugh: "everyone knows steamed brussels sprouts smell like farts, and don't taste very good." 😂 
- [ ] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 
> Commit message was `class_1_example_object.txt`. Make sure that you start with a verb and capital letter. 

Class #2 Checklist
- [ ] The three attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [ ] The three methods I chose for **Class #2** represent behaviors or actions.
- [x] I described what the methods do in **Class 2**.
- [x] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 
> For a class called `Furniture`, make sure that all of your attributes and methods could apply to *any* furniture. It looks like some of the attributes and methods defined could only apply to a square table (like `Chairs_per_square_table` and `count_chairs`). If I were to make a `dresser` object using the `Furniture` class as it stands now, those attributes and methods would not be able to be used. 
> In addition, `check_dining_room_inventory` is a method that should be defined for a `Dining_Room` class, not a furniture class. (Think of my above example with dresser: I wouldn't say `dresser.check_dining_room_inventory` since it wouldn't be a responsibility of a dresser. 

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 

### Assessment Results
- [ ] Technical Ready
- [x] Pending
> Next Steps:
> Create one more file called class_3.txt and define a class that you would find in a city. Be sure that the methods are all actions of/for that specific class. Create another file called class_3_example_object.txt and give the attributes and methods for a specific object of that class.
- [ ] Not Technical Ready
